### ISSUE TITLE
Not Dropping Gems?

### ISSUE THREAD

**Issue by themasterswordmaster** [TheDeathlyCow/more-geodes#19]
The fully grown clusters (Diamond, Emerald, and Quartz) arent dropping any resources, in the version included with Better Minecraft Fabric 1.19.2

**Comment by themasterswordmaster** [comment]
Nevermind, i found the reason, the Soul Steel pickaxe (for some reason) doesnt drop the resources, but vanilla pickaxes do :\

**Comment by TheDeathlyCow** [comment]
I don't know what the Soul Steel pickaxe is but my guess is they forgot to add their pickaxe to the item tag `#minecraft:clusters_max_harvestables`.
