### ISSUE TITLE
Crash on Game startup

### ISSUE THREAD

**Issue by Frost-wood** [TheDeathlyCow/more-geodes#2]
Crash on game startup

--- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/17/21, 2:02 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'geodes'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_5585.<init>(net.minecraft.class_4651, net.minecraft.class_4651, net.minecraft.class_4651, net.minecraft.class_4651, net.minecraft.class_4651, java.util.List)'
	at com.github.thedeathlycow.gen.features.ModConfiguredFeatures.<clinit>(ModConfiguredFeatures.java:15)
	at com.github.thedeathlycow.gen.features.ModFeatures.registerFeatures(ModFeatures.java:20)
	at com.github.thedeathlycow.MoreGeodes.onInitialize(MoreGeodes.java:21)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$zlb000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:36)
	at net.minecraft.class_128.method_560(class_128.java:266)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5377510912 bytes (5128 MiB) / 6048186368 bytes (5768 MiB) up to 11978932224 bytes (11424 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon (TM) R9 200 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x6811
	Graphics card #0 versionInfo: DriverVersion=27.20.14501.18003
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26041.14
	Virtual memory used (MB): 15683.64
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 232.34
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx11424m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		architectury: Architectury 2.0.9
		arfo: Artificial Foliage 1.0
		atlantis: Atlantis 2021.6.11-1.17-1.1.0-fabric
		attributefix: Attribute Fix {FABRIC} 1.0.1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		betternether: Better Nether 5.1.0
		blockus: Blockus 2.2.1+1.17
		blue_endless_jankson: jankson 1.2.1
		cardinal-components-base: Cardinal Components API (base) 3.0.0-nightly.1.17-pre2
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0-nightly.1.17-pre2
		charm: Charm 3.1.3
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		clumps: Clumps fabric-1.17-7.0.0.2
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_draylar_omega-config_omega-config: omega-config 1.0.8-1.17
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.4-1.17
		controlling: Controlling For Fabric 1.1.2
		customportalapi: Custom Portals 0.0.1-beta32-1.17
		dankstorage: Dank Storage 2.0a-1.17
		darkness: True Darkness 1.6.72
		dawn: Dawn API 2.0.3
		dazzle: Dazzle 2 1.0
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		enchantmentdescriptions: Enchantment Descriptions 3.0.11
		expandedstorage: Expanded Storage 7.0.0-alpha.25
		fabric: Fabric API 0.35.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+84310a227d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c3d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fake-player-api: Fake Player API 0.2.0
		fallingtree: FallingTree 2.11.5
		farmersdelight: Farmer's Delight 1.17-0.1.0
		fasttransferlib: Fast Transfer Lib 0.4.2
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.13
		geckolib3: Geckolib 3.0.5
		geodes: More Geodes 1.0.0
		glassdoor: Glass Doors 1.5.0-1.16
		indrev: Industrial Revolution 1.10.0-alpha.3
		inventorysorter: Inventory Sorter 1.7.9-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kyrptconfig: Kytpt Config 1.1.10-1.17
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.1.2-BETA+1.17
		lightoverlay: Light Overlay 6.0.0
		magna: Magna 0.3.0-1.17-pre4
		minecraft: Minecraft 1.17
		mining_dims: Mining Dimensions 1.1.3
		mo_glass: Mo Glass 1.5-MC1.17
		morevillagers-fabric: MoreVillagersFabric 2.0.0-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-1.17
		omega-config: OmegaConfig 1.0.8
		openworlds: Open Worlds 1.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		patchouli: Patchouli 1.17-52-FABRIC-SNAPSHOT
		pipe: Pipe 1.3.1
		promenade: Promenade 2.1.2
		rightclickharvest: Right Click Harvest 1.2.3
		roughlyenoughitems: Roughly Enough Items 6.0.251-alpha
		shulkerutils: shulkerutils 1.0.1-1.17
		simple_cobblestone_generator: Simple cobblestone generator 1.1.2
		somnus: Somnus API 0.0.12-1.17
		spawnermod: Enhanced Mob Spawners 1.0.0
		staffofbuilding: Staff of Building 1.3.0-1.17
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.7
		team_reborn_energy: Energy 0.1.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		toolstats: Tool Stats 2.0.1
		upgradedshulkers: Upgraded Shulkers 1.0.1-1.17
		voxelmap: VoxelMap 1.10.15
		waystones: Waystones 2.0.1
		wthit: wthit 3.5.3
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by TheDeathlyCow** [comment]
You are on 1.0.0, which is made for a different version of Mineraft. Use the latest version (1.0.4) for compatibility with the latest release.

**Comment by Frost-wood** [comment]
thanks!

**Comment by GalacticRuler** [comment]
I still get this on 1.0.4

**Comment by TheDeathlyCow** [comment]
Please post your full crash log.

**Comment by campbebj** [comment]
this is the error im getting. i think its the same one. https://pastebin.com/SfZGDf2j
