### ISSUE TITLE
[Issue] Config file not generating for 1.6.1

### ISSUE THREAD

**Issue by Nekkok** [TheDeathlyCow/more-geodes#26]
Hi! I want to disable the latest new geodes for my modpack but the geodes.properties is not generating in my config folder. I also tried to make a datapack to disable them but is not working at all.

You can take a look here: 
[data.zip](https://github.com/TheDeathlyCow/more-geodes/files/10252995/data.zip)

**Comment by TheDeathlyCow** [comment]
The config file does not generate, you have to create it.

The reason your datapack is not working is that the `replace` field of your tags is set to `false`. Set it to `true` and it should work.
