### ISSUE TITLE
[Fabric 1.20.1] Hard dependency on Carpet mod (movableAmethyst mixin causes crash)

### ISSUE THREAD

**Issue by Questwizard** [TheDeathlyCow/more-geodes#34]
More Geodes 1.8 for 1.20.1 crashes if Carpet is not installed. It looks like the mod is still trying to apply the movableAmethyst mixin even if Carpet isn't installed. No big deal, just probably not intended behavior since Carpet is marked as optional on the Modrinth page. Using Fabric loader 0.14.21, API 0.83.1.

Log:
[latest.log](https://gist.github.com/Questwizard/e7cf55d6b7793d41b18c6759951606b8)

**Comment by TheDeathlyCow** [comment]
Thanks for the report, this is indeed not intended behaviour!
