### ISSUE TITLE
Warning in the console

### ISSUE THREAD

**Issue by RDKRACZ** [TheDeathlyCow/more-geodes#4]
`[14:12:42] [main/WARN]: Reference map 'more-geodes-refmap.json' for geodes.mixins.json could not be read. If this is a development environment you can ignore this message`

**Comment by TheDeathlyCow** [comment]
Ignoring this issue as the mod does not make use of mixins and this seems to do nothing.

**Comment by RDKRACZ** [comment]
>mod does not make use of mixins

Then you should remove the mixin part from the fabric.mod.json file (and remove geodes.mixins.json) to fix this issue.
