### ISSUE TITLE
[Fabric][1.19.2] More Geodes compat issues with Applied Energistics 2

### ISSUE THREAD

**Issue by Rabbit-Queen1** [TheDeathlyCow/more-geodes#40]
More Geodes causes important items in Applied Energistics 2 (v12.9.8) to disappear from creative menu/JEI/EMI.

**Comment by TheDeathlyCow** [comment]
What items specifically? And does this happen on 1.20?

**Comment by TheDeathlyCow** [comment]
Closed for lack of information/inactivity
