### ISSUE TITLE
Piglins rapidly consume entire stack of Pyrite after first barter

### ISSUE THREAD

**Issue by Lumine139637659** [TheDeathlyCow/more-geodes#52]
https://github.com/TheDeathlyCow/more-geodes/assets/123864592/1700a4b6-3543-4393-8621-40515388105f
我使用Pyrite Chunk与猪灵交易，猪灵快速拾取了所有的Pyrite Chunk而不提供物品。
I used the Pyrite Chunk to trade with the Piglin, and the Piglin quickly picked up all the Pyrite Chunks without providing any items.

使用curseforge最新的1.1.1（forge）
Using the latest 1.1.1（forge） of curseforge

**Comment by TheDeathlyCow** [comment]
piglins not giving items when trading pyrite is intentional, it's not real gold after all. however they should realise it's fake and aggro on the player, and not just pick up all the items like that
