### ISSUE TITLE
New Echo Locator support for modded ores

### ISSUE THREAD

**Issue by NolanHewitt** [TheDeathlyCow/more-geodes#56]
Would it be possible to let us add which blocks the new version of the echo locator can detect in a config file so we can add support for it to work with modded ores?

**Comment by TheDeathlyCow** [comment]
The echo locator uses the block tag `geodes:echo_locatable` to determine which blocks it can detect. You can add or remove whatever modded blocks you wish to this tag with a datapack. The tag by default includes the conventional ores tag, so it should work out of the box with any modded ores that use that conventional tag.

**Comment by NolanHewitt** [comment]
Ah ok, looks like it detects c:ores, and a couple of the mods I'm using don't have that tag added to their ores. Adding that to them with a datapack fixed that issue. Thank you.
