### ISSUE TITLE
[Feedback] Geodes spawn too close to the surface in mountain biomes

### ISSUE THREAD

**Issue by Quizer9O8** [TheDeathlyCow/more-geodes#7]
Emerald Geodes pop up way too often near the surface at Jagged Peaks, Frozen Peaks, Stony Peaks, Snowy Slopes, and Meadow biomes them partly or fully exposed. The abundance of these geodes sometimes destroys  villages in the Meadow when spawning in. It would be great if there was a way to configure this manually.

The way geodes presented themselves was very noticeable when using the terrain mod Terralith 2.0

**Comment by TheDeathlyCow** [comment]
Could you provide the seed, coordinates, and modlist, or at least a screenshot? I would like to investigate this further but that is hard without more information. Also, note that Terralith has its own version of emerald geodes.

**Comment by Quizer9O8** [comment]
Seed: 4105231
Cords:  -90 161 -335
Mod Version: Terralith_v2.0.5_~_Fabric+Forge.jar + more-geodes-1.2.0.jar
![image](https://user-images.githubusercontent.com/19509275/146560347-bdf71416-c9eb-4c2d-8a02-53911863543f.png)

AFAIK I haven't seen any Emerald Geodes of Terralith. 
I suppose they use vanilla blocks of emerald and don't have any compatibility with this mod.
Still having a configuration file where you can manually change the conditions for geodes to spawn and detect villages and avoid planting themselves in road/structure segments would be great.

**Comment by TheDeathlyCow** [comment]
Ok well, I can't really find this affecting any villages as you described in your original comment. They are supposed to generate high up in mountains to match emerald ore; the fact they stick out is just a by-product of that. I may set up a config file to adjust the heights though. One workaround you can use for now is to create a datapack and override the `geodes:emerald_geode` placed feature. Just make sure that is in the right namespace folder. 

Here's an example you can use:
In file `data/geodes/worldgen/placed_feature/emerald_geode.json`
```json
{
    "feature": "geodes:emerald_geode",
    "placement": [
        {
            "chance": 24,
            "type": "minecraft:rarity_filter"
        },
        {
            "type": "minecraft:in_square"
        },
        {
            "height": {
                "min_inclusive": {
                    "above_bottom": 6
                },
                "max_inclusive": {
                    "absolute": 64
                },
                "type": "minecraft:uniform"
            },
            "type": "minecraft:height_range"
        },
        {
            "type": "minecraft:biome"
        }
    ]
}
```

**Comment by Quizer9O8** [comment]
The way geodes intersect with villages is probably the fact that these villages spawn at the edge of a mountain biome thus sometimes A geode can get in the way.

**Comment by TheDeathlyCow** [comment]
Emerald geode generation now matches amethyst geode generation as of [2a987f8](https://github.com/TheDeathlyCow/more-geodes/commit/2a987f83feb9186f37ed6f1808f1fdfd49c82f9b).
