### ISSUE TITLE
Emerald Geode block should be made with Emerald shards, not emeralds.

### ISSUE THREAD

**Issue by Angular-Angel** [TheDeathlyCow/more-geodes#9]
This would be more consistent with amethyst geodes, and make it harder to get the emerald geode block, as it's much easier to farm emeralds from villagers than to farm emerald shards from the geodes, unless you choose to live in the mountains. And making the Emerald Geode block harder to get would make it feel much more special.

**Comment by TheDeathlyCow** [comment]
I removed emerald shards from survival mode in version 1.0.5, as I felt they added an unnecessary level of complexity and were actually inconsistent with other gem type items such as diamonds and even amethysts (as they required some sort of processing to become useful - amethyst shards are immediately useful). 

Considering your feedback about obtaining emeralds from villagers: trading with villagers is a very manual and tedious process. You can automate the collection of emeralds by destroying an Emerald Cluster with a piston (or by some other method), making it much easier to just leave it going for a while and come back to it when you need emeralds. 

I will consider your request about crafting geode blocks. Perhaps it could be crafted with buds (obtained using silk touch) instead?

**Comment by Angular-Angel** [comment]
I actually liked the emerald shard idea. Sure, they are a little inconsistent with other gems, but I feel it makes sense, and I appreciate the added complexity.
